### ISSUE TITLE
OnErrorResumeNext source not disposed on error

### ISSUE THREAD

**Issue by glenringer** [akarnokd/async-enumerable-dotnet#11]
`OnErrorResumeNext` does not dispose `source` enumerator on error.

Failing test:

```c#
[Fact]
public async void Error_DisposeSource()
{
    var disposed = false;
    await AsyncEnumerable.Error<int>(new Exception())
        .DoOnDispose(() => disposed = true)
        .OnErrorResumeNext(e => AsyncEnumerable.Empty<int>())
        .AssertResult();
    Assert.True(disposed);
}
```

**Comment by akarnokd** [comment]
Thanks again. I'm currently not developing this library as I wait for the standardization of the `IAsyncEnumerable` interfaces in C# 8, which may include an extra `CancellationToken` passed around. You are welcome to post PRs with fixes though.

**Comment by akarnokd** [comment]
Fixed in https://github.com/akarnokd/async-enumerable-dotnet/commit/b6e3eed5f88f8e0958daf8e766f7fb14ef4b1548.
