### ISSUE TITLE
Support netstandard2.0

### ISSUE THREAD

**Issue by fubar-coder** [akarnokd/async-enumerable-dotnet#2]
The current target framework is .NET Core 2.1, which means that neither the "full" .NET Framework nor mobile development using Xamarin is supported.

You can get access to `IObservable<T>` by adding `System.Reactive` as package reference.

**Comment by akarnokd** [comment]
I have no idea how to do that. I've just started out as "New project > .NET Core Library" in VS.  PR welcome.

**Comment by akarnokd** [comment]
Done vie https://github.com/akarnokd/async-enumerable-dotnet/commit/196fdbe0e25710cd8c5ff25b50e5627e5673ef8e and released as [0.0.1.2](https://www.nuget.org/packages/akarnokd.async-enumerable-dotnet/0.0.1.2) to NuGet.
