### ISSUE TITLE
Switch disposal delay

### ISSUE THREAD

**Issue by Lukazoid** [akarnokd/async-enumerable-dotnet#28]
It seems that the switch operator disposal delays until the outer source enumerable publishes an additional item.

This example takes 10 seconds before the exception is actually observed despite the exception being thrown immediately:

    async Task Main()
    {
        try
        {
            await foreach (var item in async_enumerable_dotnet.AsyncEnumerable.Interval(TimeSpan.Zero, TimeSpan.FromSeconds(10))
                .Select(x => async_enumerable_dotnet.AsyncEnumerable.Just(x))
                .Switch())
            {
                Console.WriteLine(item);
    
                throw new Exception();
            }
        }
        catch (Exception)
        {
            Console.WriteLine("Observed Exception");
        }
    
        Console.WriteLine("Continuing");
    }

Is there a reason the source `IAsyncEnumerator<T>` is not disposed of immediately?

In my particular situation this results in the application stalling because the outer async enumerable is infinite but in some situations it may never proceed to publish another item, however I would like the exception to be propagated.

**Comment by akarnokd** [comment]
I'd guess when the outer gets disposed, that path should trigger a token-cancellation for the current source. I'll see if I can fix it.

**Comment by akarnokd** [comment]
Looks like one has to always create a custom `CancellationTokenSource`s and issue a cancels upon `DisposeAsync`.

**Comment by Lukazoid** [comment]
Is that something consumers of the library will need to do? Or something the Switch operator can do for us?

**Comment by akarnokd** [comment]
It appears to be the library's responsibilities. I'll post fixes to operators shortly.

**Comment by akarnokd** [comment]
Fixed and published in v0.0.4.
