### ISSUE TITLE
ToListAsync support (and similar)

### ISSUE THREAD

**Issue by fubar-coder** [akarnokd/async-enumerable-dotnet#3]
An additional extension method would be useful:

```cs
Task<List<T>> ToListAsync(this IAsyncEnumerable<T> source);
```

This would allow creating a list with:

```cs
var list = await asyncSequence.ToListAsync();
```

This avoids the blocking usage of `ToEnumerable`.

**Comment by akarnokd** [comment]
I haven't prioritized most of the derivable operators like the one you requested:

```cs
await source.Collect(() => new List<T>(), (a, b) => a.Add(b)).FirstTask();
```

You are welcome to post a PR with a direct implementation placed into a static class, just like [impl/ForEach.cs](https://github.com/akarnokd/async-enumerable-dotnet/blob/master/async-enumerable-dotnet/impl/ForEach.cs).
