### ISSUE TITLE
A couple of issues in the ZipArray class

### ISSUE THREAD

**Issue by theodorzoulias** [akarnokd/async-enumerable-dotnet#50]
I reviewed the source code of the [`ZipArray`](async-enumerable-dotnet/impl/Zip.cs) class, and I am bringing to your attention a couple of issues that I observed. The [`ZipArray.ZipArrayEnumerator.MoveNextAsync`](https://github.com/akarnokd/async-enumerable-dotnet/blob/9f710ff9229cc5436a60a7a08bcf4d442d989431/async-enumerable-dotnet/impl/Zip.cs#L71) method calls concurrently the `MoveNextAsync` of the underlying enumerators. There are two issues in this method:

1. In case one `await _tasks[i].ConfigureAwait(false)` returns `false`, the remaining value-tasks in the `_tasks` array are not awaited, and they become essentially fire-and-forget tasks. When the caller calls subsequently the `ZipArray.ZipArrayEnumerator.DisposeAsync`, the `DisposeAsync` of the underlying enumerators might be called concurrently with pending asynchronous `MoveNextAsync` operations. Many `IAsyncEnumerable<T>` implementations do not allow this kind of concurrency, and throw an exception (`InvalidOperationException`) if the `DisposeAsync` is called while a `MoveNextAsync` is still in-flight.

2. In case one `await _tasks[i].ConfigureAwait(false)` throws an exception, the linked `CancellationTokenSource`s are not canceled, and so the `ZipArray.ZipArrayEnumerator.MoveNextAsync` does not complete with the maximum responsiveness. This is a minor issue, since it does not compromise the correctness of the implementation.

As a side note, I am not sure why each underlying `IAsyncEnumerator<TSource>` is associated with a dedicated `CancellationTokenSource`. It seems to me that a single linked `CancellationTokenSource` could serve all of them just as well.

**Comment by akarnokd** [comment]
I wrote this years ago. Is anybody even using this library? How did you come to it?

I'll fix the issues but I'm not actively supporting this library due to lack of interests.

**Comment by akarnokd** [comment]
Alright, fixed the issue.

I'm not sure about the `MoveNextAsync` responsiveness. I presume it could be solved by not directly awaiting each inner source at the cost of adding more coordination for when `DisposeAsync` would be invoked early.

**Comment by theodorzoulias** [comment]
> I wrote this years ago. Is anybody even using this library?

I have no idea. Someone upvoted yesterday an answer of mine in a [StackOverflow question](https://stackoverflow.com/questions/59500430/how-to-await-multiple-iasyncenumerable "How to await multiple IAsyncEnumerable"), I noticed that your library was suggested in another answer as a solution, so I gave it a quick review. :-)
