### ISSUE TITLE
Correction to wiki paragraph on why ValueTask is used

### ISSUE THREAD

**Issue by jnm2** [akarnokd/async-enumerable-dotnet#7]
https://github.com/akarnokd/async-enumerable-dotnet/wiki/Writing-operators#iasyncdisposable:

> Note that the design uses `ValueTask` instead of `Task` as there is likely enough cases where the method can run synchronously and thus the execution could avoid creating task objects and continuation handlers altogether.

As I understand it, this is not the reason. Since no result value is returned upon awaiting, the return type `Task` itself is sufficient to make the *synchronous* case cheap (return `Task.CompletedTask`). Even `ValueTask<bool>` doesn't improve on returning cached `Task<bool>` for synchronous cases.

The selling point for nongeneric `ValueTask` versus `Task` is only in the *asynchronous* case. .NET Core introduces `IValueTaskSource` which can be used instead of `Task` to drive the `ValueTask` for multiple asynchronous waits with only a single allocation.

References:

- `https://github.com/dotnet/corefx/issues/27445`
- `https://github.com/dotnet/apireviews/pull/72#discussion_r228349060`

**Comment by akarnokd** [comment]
I've drawn my understanding from the API spec: https://github.com/dotnet/corefx/issues/32640

> ValueTask instead of Task. The original design called for MoveNextAsync to return Task<bool> and DisposeAsync to return Task. That works well when MoveNextAsync and DisposeAsync complete synchronously, but when they complete asynchronously, it requires allocation of another object to represent the eventual completion of the async operation. By instead returning ValueTask<bool> and ValueTask, an implementation can choose to implement IValueTaskSource and reuse the same object repeatedly for one call after another; in this fashion, for example, the compiler-generated type that's returned from an iterator can serve as the enumerable, as the enumerator, and as the promise for every asynchronously-completing MoveNextAsync and DisposeAsync call made on that enumerator, such that the whole async enumerable mechanism can incur overhead of a single allocation.

**Comment by jnm2** [comment]
Yes, that underscores my point. As it says: "[`Task`] works well when MoveNextAsync and DisposeAsync complete **synchronously**, but when they complete **asynchronously**, it requires allocation of another object to represent the eventual completion of the async operation."

It's the asynchronous case that motivates the use of `ValueTask`, not the synchronous case as https://github.com/akarnokd/async-enumerable-dotnet/wiki/Writing-operators#iasyncdisposable currently states: "as there is likely enough cases where the method can run synchronously."

|                                | Synchronous case | Asynchronous case                                |
|--------------------------------|------------------|--------------------------------------------------|
| `Task`, `Task<bool>`           | 0 allocations    | Allocates 1 `Task<>` per call                    |
| `ValueTask`, `ValueTask<bool>` | 0 allocations    | Reuses the same `IValueTaskSource` for all calls |

**Comment by akarnokd** [comment]
Updated the sentence.

**Comment by jnm2** [comment]
@akarnokd I see a typo: `it can reduces` should be `it can reduce`. Other than that, looks great! Thank you for doing this article, it's awesome!
Also, it's fine with me if you don't link to this issue from the wiki. Whatever you prefer.
